name: Deploy Sovica
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    if: github.event_name == 'push'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: yarn install
      - name: yarn sharp magic
        run: yarn add sharp --ignore-engines
      - name: Run tests
        run: yarn test
  deploy:
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn install --production
      - name: yarn sharp magic
        run: yarn add sharp --ignore-engines
      - name: Build
        run: yarn build && tar -czvf sovica.tar.gz ./build
      - name: Copy file via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.REMOTE_HOST }}
          username: ${{ vars.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: './sovica.tar.gz'
          target: ${{ vars.HOME_DIR }}
      - name: Unpack on remote
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.REMOTE_HOST }}
          username: ${{ vars.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: 'tar -xzvf  ${{ vars.HOME_DIR }}/sovica.tar.gz -C  ${{ vars.HOME_DIR }} && rm -rf sovica && mv build sovica'
